# 世帯情報入力端末の設定

# 避難所番号（この避難所番号のデータの登録のみ有効になる）
shelter_id: 19

# XBee 関連の設定
xbee:
  # XBee Coordinator デバイスファイルのパス
  port: /dev/ttyUSB0
  # ボーレート
  rate: 9600

# ログを記録するレベル
# debug, info, warn, error, fatal
log_level: info
